#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once 'vendor/autoload.php';

use Quotes\QuoteGenerator;
use Quotes\Source\Trump;
use Quotes\Strategy\Random;

$source    = new Trump();
$strategy  = new Random();
$generator = new QuoteGenerator($source, $strategy);

var_dump($generator->retrieve());
